Feat crud orders
tahnamao/scrimart-api pull request #47
Opened 2021-01-29 21:11 UTC by tbrrt11

closes #6 , closes #12 , closes #13

2021-01-29 21:28 UTC, rivanbello commented on src/modules/orders/infra/http/controllers/OrderController.ts
> +  public async create(request: Request, response: Response): Promise<Response> {
Normalmente é legal deixar os métodos na ordem, para quem for dar manutenção se deparar com algo padronizado.

2021-01-29 21:37 UTC, rivanbello requested changes
Algumas ponderações.  😎

2021-01-29 21:37 UTC, rivanbello commented on src/modules/orders/infra/http/controllers/OrderController.ts
> +      if (!isValid(yearDate)) {
Esse tipo de validação faço dentro da service.

2021-01-29 21:37 UTC, rivanbello commented on src/modules/orders/infra/typeorm/entities/Order.ts
> +  @Expose()
Porque o Expose aqui?

2021-01-29 21:37 UTC, rivanbello commented on src/shared/infra/typeorm/migrations/1611888002235-AddOrders.ts
> +export class AddOrders1611888002235 implements MigrationInterface {
Por preciosismo colocar um default sempre aqui please.

2021-01-29 22:57 UTC, tbrrt11 commented on src/modules/orders/infra/http/controllers/OrderController.ts
> +  public async create(request: Request, response: Response): Promise<Response> {
Ok

2021-01-29 23:00 UTC, tbrrt11 commented on src/modules/orders/infra/http/controllers/OrderController.ts
> +      if (!isValid(yearDate)) {
Ok

2021-01-29 23:01 UTC, tbrrt11 commented on src/modules/orders/infra/typeorm/entities/Order.ts
> +  @Expose()
Estava tentando fazer o eager funcionar no POST /orders, mas ainda não consegui...

2021-01-29 23:03 UTC, tbrrt11 commented on src/shared/infra/typeorm/migrations/1611888002235-AddOrders.ts
> +export class AddOrders1611888002235 implements MigrationInterface {
Ok

2021-01-30 00:17 UTC, rivanbello approved these changes

2021-01-30 00:17 UTC, merged